# Generated by Django 2.2.2 on 2019-08-01 00:54

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('academic_year', models.CharField(max_length=30)),
                ('semester', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', app.models.ExtraFileField(upload_to=app.models.task_path)),
                ('file_hash', models.CharField(max_length=255)),
                ('daily_submission_limit', models.PositiveSmallIntegerField(default=3)),
                ('max_upload_size', models.IntegerField(default=5120)),
                ('run_time_limit', models.IntegerField(default=60)),
                ('max_image_size', models.IntegerField(default=1000000)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('leaderboard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.Course')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='app.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=app.models.submission_path)),
                ('docker', models.CharField(blank=True, max_length=255, null=True)),
                ('runner', models.CharField(choices=[('PY', 'Python'), ('DO', 'Docker')], default='PY', max_length=2)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('E', 'Error'), ('D', 'Done')], default='Q', max_length=1)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADM', 'Admin'), ('GUE', 'Guest'), ('STU', 'Student'), ('LEC', 'Lecturer'), ('TA', 'Teaching Assistant')], default='STU', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(through='app.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'academic_year', 'semester')},
        ),
    ]
