# Generated by Django 2.2.4 on 2019-11-09 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20191008_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=9)),
                ('diff', models.TextField(blank=True, null=True)),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='app.Submission')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity', to='app.Submission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='app.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task', 'submission', 'related')},
            },
        ),
    ]
