# Generated by Django 2.2.4 on 2019-11-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191110_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
