# Generated by Django 2.2.4 on 2020-08-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='name',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
