# Generated by Django 3.2.6 on 2021-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.AddField(
            model_name='worker',
            name='channel_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
